name: preplens_student_app
description: PrepLens Student Learning App with AI-Powered Personalized Learning

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  cupertino_icons: ^1.0.6
  
  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # UI enhancements
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Loading indicators
  flutter_spinkit: ^5.2.0
  
  # Toast messages
  fluttertoast: ^8.2.4
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Charts and progress
  fl_chart: ^0.66.0
  
  # Animations
  lottie: ^2.7.0
  
  # Pin code input
  pin_code_fields: ^8.0.1
  
  # Date picker
  intl: any
  
  # Icons
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true